### ISSUE TITLE
'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by kenvernaillenvub** [adafruit/Adafruit_ADS1X15#19]
Hello,
I get the following error (very random):

line 223 in readADCSingleEnded >
val = (result[0] << 8) | result[1])
**TypeError**: 'int' object has no attribute '**getitem**'

What can this be? How can I solve it?

**Comment by caternuson** [comment]
That looks like a Python or CircuitPython related issue. This is the Arduino library.
