### ISSUE TITLE
Can we use this module with Energia(MSP microcontrollers)????

### ISSUE THREAD

**Issue by hemangjoshi37a** [adafruit/Adafruit_ADS1X15#25]
I am using MSP430G2553 and MSP430G5529 microcontrollers with their respective lauch pad. Please help me how to use this library for MSP microcontrollers.
Thank you.

**Comment by caternuson** [comment]
If it has an Arduino Board Support Package and there are available I2C ports, then in theory it should work. But you should test to verify.
