### ISSUE TITLE
two differential signasl

### ISSUE THREAD

**Issue by rcanha** [adafruit/Adafruit_ADS1X15#38]
I'm trying to read two differential signals by making a small change in the differential.ino file provided by your library.
Basically I include a new variable int16_t and assign it differential reading through the ads.readADC_Differential_2_3 () command.

The problem that the displayed result is is the same reading as that obtained with ads.readADC_Differential_0_1 () - the actual signals are different.

Is there a problem with the library because when I use ads.readADC_Differential_2_3 () without using ads.readADC_Differential_0_1 () do I get the correct reading but using both I have repeated differential readings?

Thanks

**Comment by caternuson** [comment]
Tested, can't recreate. Wired 0 and 3 to voltage divider output and 1 and 2 to GND. Values track as expected. One is the invert of the other.

![ads_dif_test](https://user-images.githubusercontent.com/8755041/75299566-459b7080-57ea-11ea-86be-2fa20bdf67f8.jpg)

```cpp
#include <Adafruit_ADS1015.h>

Adafruit_ADS1115 ads;

void setup() {
  Serial.begin(9600);
  while (!Serial) {};

  ads.begin();
}

void loop() {
  Serial.print("0_1: ");
  Serial.print(ads.readADC_Differential_0_1());
  Serial.print("  2_3: ");
  Serial.println(ads.readADC_Differential_2_3());
  delay(500);
}
```
![image](https://user-images.githubusercontent.com/8755041/75299668-83989480-57ea-11ea-9eda-34b2087cb162.png)
