### ISSUE TITLE
Arduino Mega not reading negative bits from ADS 1115

### ISSUE THREAD

**Issue by bcantrell500** [adafruit/Adafruit_ADS1X15#4]
Hello,

We are trying to read a voltage which ranges from -4V to +4V from a signal conditioner in differential mode using the ADS1115 set to a gain of one. As of right now one wire from the signal conditioner is connected to A0 on the ADC with the other connected to A1. When the signal conditioner outputs a positive voltage, we have no problem reading it all the way to the expected +4V. However, when the signal conditioner outputs a negative voltage, the value starts going negative, will hover around -678 and then sometimes spike to -32768 as the voltage decreases from zero. All in all we are unable to read negative voltage. 

I'm not sure if I have a wiring problem? Do I need to set up a reference in differential mode? Do I need to initialize the ADC into differential mode because it's naturally initialized to single-ended? I'm a bit lost and would very much appreciate any help.

Thank you!

**Comment by jamesfowkes** [comment]
This is a very old issue, but the reason it's probably not working is that the ADS1115 doesn't support negative voltages with respect to GND.

The differential mode measures the difference between two voltages, but they must both be >= GND.

**Comment by caternuson** [comment]
Closing. This is probably as @jamesfowkes says above.

From ADS1115 Datasheet, pg. 12:
![image](https://user-images.githubusercontent.com/8755041/75297899-e2a7da80-57e5-11ea-9f20-f6fbb247d4ec.png)
