### ISSUE TITLE
ESP32 Using Adafruit_ADS1115 whith Two I2C Bus Interfaces

### ISSUE THREAD

**Issue by nusatiy** [adafruit/Adafruit_ADS1X15#48]
Hello friends.
Could you explain how this works when used?
#include <Wire.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_BME280.h>

#define SDA_1 27
#define SCL_1 26

#define SDA_2 33
#define SCL_2 32

TwoWire I2Cone = TwoWire (0);
TwoWire I2Ctwo = TwoWire (1);

How do I tell the Adafruit ADS1115 library that I need to use the second twoWire (1) bus?

I tried pointing as Adafruit_ADS1115 ads1115 (& I2Ctwo);
This does not work.

**Comment by caternuson** [comment]
Pass the bus in when you call begin(). This is a recent change added with #58.
