### ISSUE TITLE
ads1115 all inputs tied together different readings

### ISSUE THREAD

**Issue by jorythompson** [adafruit/Adafruit_ADS1X15#50]
I am reading all four inputs (non-differential) on an ADS1115 with a raspberry pi.  
For grins, I tied all inputs together and then to ~3V (I am using a voltage divider to read 9V).
I was surprised to see that all values are slightly different (as much as 11):

22045
22043
22051
22040

Is this reasonable?  The wires are all in a breadboard and I have reseated them several times.

**Comment by ladyada** [comment]
yes ADCs have some offset, you can calibrate the offset in your code if neede
