### ISSUE TITLE
should be uint16_t because readADC_SingleEnded() returns uint16_t not int16_t

### ISSUE THREAD

**Issue by Alvedro** [adafruit/Adafruit_ADS1X15#54]
https://github.com/adafruit/Adafruit_ADS1X15/blob/6560438adca9f0a7d9c432e3cca35f0f18778a94/examples/singleended/singleended.ino#L33

**Comment by caternuson** [comment]
It's generally OK since the register value is signed. What might be even better is to change the return to int16_t, even though no negative values will be generated.

Are you finding the implicit cast ends up causing issues?
