### ISSUE TITLE
Version 2.0 crashes at `begin()`

### ISSUE THREAD

**Issue by David-OConnor** [adafruit/Adafruit_ADS1X15#63]
Hi. I've been using this library for a while with no issues, but version 2.x crashes at `begin()`. If I revert to 1.x, (And make the appropriate module name and address location changes), it works again. How would you troubleshoot this?

Related: It's worth updating [this Adafruit guide](https://learn.adafruit.com/adafruit-4-channel-adc-breakouts/arduino-code) with the new module name `ADX1x15`, and the address going in `begin()` instead of the constructor. And adding how to set a custom address to the examples folder here.

Thank you.

**Comment by caternuson** [comment]
What main board are you using?

**Comment by David-OConnor** [comment]
Arduino Uno

**Comment by caternuson** [comment]
Just tested here and it works OK. The 2.x updates did have some breaking changes, so you may need to make some minor changes to any existing code. To sanity check, try using one of the examples from this library.

This was using the single ended example:
https://github.com/adafruit/Adafruit_ADS1X15/blob/master/examples/singleended/singleended.ino
with A0 and A2 tied to the voltage divider. A1 tied to GND. A3 tied to 5V.

![uno_ads_test](https://user-images.githubusercontent.com/8755041/113211928-f7497400-922a-11eb-9f0e-f197d9df4f0e.jpg)

![Screenshot from 2021-03-31 14-05-36](https://user-images.githubusercontent.com/8755041/113211975-03353600-922b-11eb-8fa4-2babe6e48f69.png)

**Comment by David-OConnor** [comment]
Thank you very much for the detailed info. Th example code works for me. I'm using this library as a dependency in the Arduino driver for a pH circuit, and am still unable to get v2.x working, but can't figure out why. My best guess is that this is related to the busio dependency change. I'm not getting an error - just a hang, and/or gibberish printed to the console. I'll troubleshoot more, and keep you posted.

**Comment by ladyada** [comment]
you're probably running out of RAM. you'll need to update to a board with more RAM memory.

**Comment by caternuson** [comment]
Closing due to lack of response. Since the library example sketch works, this may either be the RAM issue or needing some slight code updates to deal with minor (breaking) changes in 2.x release.
