### ISSUE TITLE
2.1.1 in 2/3 gain mode, values loose resolution 

### ISSUE THREAD

**Issue by OZ2CPU-thomas** [adafruit/Adafruit_ADS1X15#65]
at voltages over 5.7V to 6.1V the values loose the last digit of analog resolution
tha tlast value become 0
it is supposed to handle 0-6,1V in a smooth full resolution way,
at input voltages under 5.7V the data do contail values in the last digit
my IC is ADS1115 so it is 16 bit

**Comment by caternuson** [comment]
The 6.144V FS range is for scaling only. The actual input range should not exceed VDD+0.3V. VDD absolute max is 5.5V.

![image](https://user-images.githubusercontent.com/8755041/114929435-a4ee8280-9de8-11eb-85b7-031954f7c47d.png)

![image](https://user-images.githubusercontent.com/8755041/114929674-f5fe7680-9de8-11eb-94a8-9111662da7b1.png)

**Comment by OZ2CPU-thomas** [comment]
THANKS !! this could explain it.. still a quite odd error, since it handle +/- voltages too ??
