### ISSUE TITLE
Adafruit_ADS1X15 Library

### ISSUE THREAD

**Issue by cesartayoun** [adafruit/Adafruit_ADS1X15#66]
i am using an ADS1115 16 bits with ESP32, i noticed that the ADS library does not have a function to check the availability of the sensor, hence if the sensor is not available the ESP32 will freeze.
any workaround for such problem ? thanks

**Comment by ladyada** [comment]
@caternuson plz make
https://github.com/adafruit/Adafruit_ADS1X15/blob/master/Adafruit_ADS1X15.cpp#L65
return the value from the i2cdev begin so it can be verified that the addr exists?

**Comment by caternuson** [comment]
@ladyada yah, should just do that regardless. i'll pr it real quick.

@cesartayoun can you share code that demonstrates the issue? wondering if the actual call to `i2cdev.begin()` is freezing?

**Comment by caternuson** [comment]
Possibly related to #64

**Comment by caternuson** [comment]
@cesartayoun Please update to the 2.2.0 release of the library:
https://github.com/adafruit/Adafruit_ADS1X15/releases/tag/2.2.0
and see if that helps.

**Comment by cesartayoun** [comment]
Hello, i tried the singleended example, no particular code to share; i will update the library and try.. thanks

**Comment by cesartayoun** [comment]
Hi again, problem solved, i modified the library as instructed above. thank you
