### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by factoryright** [adafruit/Adafruit_ADS1X15#7]
In the following file:
https://github.com/adafruit/Adafruit_ADS1X15/blob/master/Adafruit_ADS1015.cpp

Line 72 is as follows:
@brief  Writes 16-bits to the specified destination register

Should be something like:
@brief  Reads 16-bits from the specified destination register.

**Comment by caternuson** [comment]
That's part of the doxy for the register write function, so seems OK. There's is also a read register function which does have that doxy.
