### ISSUE TITLE
ADC_SingleEnded sending fixed values if analog < 0.4V (voltage follower between sensors and ADC)

### ISSUE THREAD

**Issue by DaniMzT** [adafruit/Adafruit_ADS1X15#72]
Hello,
First of all, thanks for the library :) I'm using it with 3 analog inputs connected to an ADS1115 (with an operation amplifier voltage follower in between), which sends the data to a NodeMCU. I'm using version 2.2.0. 
My problem is that there is a voltage offset when I read the inputs in NodeMCU, even using the example "singleended" from the library. The voltage of the inputs is around 80-90 mV (measured in relation to ADS1115's GND) but in the serial monitor I'm reading 0.4V, so there are 300 mV offset.
In my particular code, I've also tried it with gain = ONE (+-4V reference, so 0.125 mV resolution) but the results are the same. 
Here a video I've just recorded as an evidence: https://www.youtube.com/watch?v=TMURcEnpoeA 
As you can see, my multimeter displays around .08 (80 mV) for A0, A1 and A2. Don't pay much attention to A3, because it was connected to an open point. Sorry if my fingers covered the action, by the way. The last measurements are just a check between ADS1115's GND and the GND of the external inputs, as they are connected.
Do you know if this is a known issue and if there is a solution? Maybe I'm missing something to take into account. If so, please let it me know. 
Thanks in advance!
Kind regards

**Comment by DaniMzT** [comment]
I've repeated the tests with another ADC, but the results are as wrong as with the other ADC. These are the ADCs used:
https://www.amazon.es/gp/product/B01N8ODF5C/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1
https://es.aliexpress.com/item/32882005440.html

**Comment by soligen2010** [comment]
I think you found your issue.  OP Amps typically have an offset.  Some op amps have a way to trim out the offset.  Also, if it is not powered with both positive and negative supply, it is very common that the op amp will not go all the way to zero (even if it is "rail to rail") - this fits your observations quite well and I think is what is happening to you.  I don't think your issue is with the ADC or the library, but is in the electronics before it.   I suggest getting rid of the op-amp unless you want to do the detailed analysis and extra engineering to compensate for the offset and ensure the output can go to zero.

**Comment by caternuson** [comment]
To verify this is a library issue, you'll need to remove the ADS1115 from the custom setup.

![setup](https://user-images.githubusercontent.com/8755041/145618773-84a0f774-a743-4475-bb84-140f4bef1af0.jpg)

A good test setup would the Feather driving the ADS115 with a trim pot voltage divider going into the ADS, all staged on a breadboard.

**Comment by DaniMzT** [comment]
> I think you found your issue. OP Amps typically have an offset. Some op amps have a way to trim out the offset. Also, if it is not powered with both positive and negative supply, it is very common that the op amp will not go all the way to zero (even if it is "rail to rail") - this fits your observations quite well and I think is what is happening to you. I don't think your issue is with the ADC or the library, but is in the electronics before it. I suggest getting rid of the op-amp unless you want to do the detailed analysis and extra engineering to compensate for the offset and ensure the output can go to zero.

Exactly that, thank you! The problem was my op.amo. wasn't rail to rail. I've set specific voltage on ADS1115 inputs directly and it was working exactly. I'm not expert on electronics so I didn't know this concept of rail-to-rail. The low output voltage of my amp (LP324N) is 0.7V when Vcc is 5V (datasheet). In my case, it was 0.4 V with Vcc=3.3.
 Sorry for bothering, the library works very well. I'll search a more accurate amp!

**Comment by caternuson** [comment]
@DaniMzT Thanks for reporting back and closing the issue.

@soligen2010 Good job finding the issue!

**Comment by DaniMzT** [comment]
> @DaniMzT Thanks for reporting back and closing the issue.
> 
> @soligen2010 Good job finding the issue!

Thank you guys for helping and developing libraries like this 👍 What a good job!
