### ISSUE TITLE
cannot import name 'ParamSpec' from 'typing_extensions'  at 04-04-raspios-bullseye

### ISSUE THREAD

**Issue by put346** [adafruit/Adafruit_ADS1X15#81]
I use 4B with 2022-04-04-raspios-bullseye-armhf.img

this is my code 
git clone https://github.com/adafruit/Adafruit_Python_ADS1x15.git 
cd Adafruit_Python_ADS1x15 
sudo python setup.py install

Then I get this problem
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/usr/lib/python3/dist-packages/typing_extensions.py)

use the following code can solve which problem
sudo pip3 install adafruit-circuitpython-ads1x15

cd examples/
sudo python simpletest.py

get new problem
RuntimeError: Could not determine default I2C bus for platform.

i2cdetect -y 1 can get  48  address 

Please , how can solve this new problem?

**Comment by caternuson** [comment]
This is an Arduino library, not a Python library. 

For using the ADS1x15 ADCs with Python on a Pi, follow the guide here:
https://learn.adafruit.com/adafruit-4-channel-adc-breakouts/python-circuitpython
